'use server'

/**
 * lib/actions/complaints.ts — CS-001 server actions (Raj demo Phase 3).
 *
 * Architectural note (echoed from migration 0048):
 *   - All actions require an authenticated user (returns Profile via the
 *     standard supabase auth helper).
 *   - Stage transitions write history rows; activity timeline rows are
 *     written by the after-update trigger from 0048.
 *   - Per-state guards (e.g. can't close before resolved) live here rather
 *     than in a generic workflow engine — keeps the module self-contained.
 *     If/when we revisit the workflow engine (REV-006), these become
 *     workflow gates.
 *   - SLA tracking deferred to CS-003. We just stamp the milestone
 *     timestamps (triaged_at, resolved_at, closed_at) as state advances.
 */

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'

type Result<T = void> = { ok: true; data: T } | { ok: false; error: string }

// ─── Auth helper ────────────────────────────────────────────────

async function requireProfile() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { ok: false as const, error: 'Not authenticated' }
  const { data: profile } = await supabase
    .from('user_profile')
    .select('id, tenant_id, role')
    .eq('id', user.id)
    .single()
  if (!profile) return { ok: false as const, error: 'Profile not found' }
  return { ok: true as const, supabase, user, profile }
}

// ─── Stage lookup (memoised per action call) ─────────────────────

async function getStageIdByKey(
  supabase: Awaited<ReturnType<typeof createClient>>,
  stage_key: string,
): Promise<string | null> {
  const { data } = await supabase
    .from('complaint_stage')
    .select('id')
    .eq('stage_key', stage_key)
    .is('tenant_id', null)  // system row
    .single()
  return (data?.id as string) ?? null
}

// ─── createComplaint ────────────────────────────────────────────

export type CreateComplaintInput = {
  title: string
  description?: string | null
  type_code: string          // e.g. 'breakdown', 'product_defect'
  severity_code: string      // e.g. 'low', 'medium', 'high', 'critical'
  firm_id: string            // required customer
  reported_by_contact_id?: string | null
  project_id?: string | null
  sales_order_id?: string | null
}

export async function createComplaint(input: CreateComplaintInput): Promise<Result<{ id: string; complaint_number: string }>> {
  const auth = await requireProfile()
  if (!auth.ok) return auth
  const { supabase, profile } = auth

  // Validation — fail fast with clear errors
  if (!input.title.trim()) return { ok: false, error: 'Title is required' }
  if (!input.firm_id) return { ok: false, error: 'Customer firm is required' }

  // Resolve type, severity, initial stage
  const { data: type } = await supabase
    .from('complaint_type_master')
    .select('id')
    .eq('code', input.type_code)
    .or(`tenant_id.is.null,tenant_id.eq.${profile.tenant_id}`)
    .limit(1)
    .single()
  if (!type) return { ok: false, error: `Unknown complaint type: ${input.type_code}` }

  const { data: severity } = await supabase
    .from('severity_master')
    .select('id')
    .eq('code', input.severity_code)
    .or(`tenant_id.is.null,tenant_id.eq.${profile.tenant_id}`)
    .limit(1)
    .single()
  if (!severity) return { ok: false, error: `Unknown severity: ${input.severity_code}` }

  const initialStageId = await getStageIdByKey(supabase, 'logged')
  if (!initialStageId) return { ok: false, error: 'System stage "logged" not configured — run migration 0048' }

  // Insert. complaint_number is auto-generated by the BEFORE INSERT trigger.
  const { data, error } = await supabase
    .from('complaint')
    .insert({
      tenant_id: profile.tenant_id,
      title: input.title.trim(),
      description: input.description?.trim() ?? null,
      type_id: type.id,
      severity_id: severity.id,
      current_stage_id: initialStageId,
      firm_id: input.firm_id,
      reported_by_contact_id: input.reported_by_contact_id ?? null,
      project_id: input.project_id ?? null,
      sales_order_id: input.sales_order_id ?? null,
      logged_at: new Date().toISOString(),
      created_by: profile.id,
      updated_by: profile.id,
    })
    .select('id, complaint_number')
    .single()

  if (error || !data) return { ok: false, error: error?.message ?? 'Insert failed' }

  // History row (audit). Trigger writes activity automatically.
  await supabase.from('complaint_stage_history').insert({
    tenant_id: profile.tenant_id,
    complaint_id: data.id,
    from_stage_id: null,
    to_stage_id: initialStageId,
    actor_id: profile.id,
    remark: 'Complaint logged',
  })

  revalidatePath('/complaints')
  return { ok: true, data: { id: data.id as string, complaint_number: data.complaint_number as string } }
}

// ─── advanceStage ────────────────────────────────────────────────

export async function advanceComplaintStage(input: {
  complaint_id: string
  to_stage_key: string
  remark?: string
}): Promise<Result<{ new_stage_id: string }>> {
  const auth = await requireProfile()
  if (!auth.ok) return auth
  const { supabase, profile } = auth

  const { data: current } = await supabase
    .from('complaint')
    .select('id, current_stage_id, assignee_id, resolution_notes')
    .eq('id', input.complaint_id)
    .single()
  if (!current) return { ok: false, error: 'Complaint not found' }

  const toId = await getStageIdByKey(supabase, input.to_stage_key)
  if (!toId) return { ok: false, error: `Unknown stage: ${input.to_stage_key}` }

  if (toId === current.current_stage_id) {
    return { ok: false, error: 'Complaint is already in that stage' }
  }

  // Stage-specific guards — keep it minimal but enforce the obvious "you
  // can't close without resolving" rule. Other transitions are permitted
  // for v1 (admin override default).
  if (input.to_stage_key === 'closed' && !current.resolution_notes) {
    return { ok: false, error: 'Cannot close without resolution notes — record resolution first' }
  }
  if (input.to_stage_key === 'in_progress' && !current.assignee_id) {
    return { ok: false, error: 'Cannot mark in-progress without an assignee — assign first' }
  }

  // Build update payload + state-specific timestamp stamping
  const patch: Record<string, unknown> = {
    current_stage_id: toId,
    updated_by: profile.id,
    updated_at: new Date().toISOString(),
  }
  if (input.to_stage_key === 'triaged' )   patch.triaged_at  = new Date().toISOString()
  if (input.to_stage_key === 'resolved') { patch.resolved_at = new Date().toISOString(); patch.resolved_by = profile.id }
  if (input.to_stage_key === 'closed' )  { patch.closed_at   = new Date().toISOString(); patch.closed_by   = profile.id }

  const { error: uErr } = await supabase
    .from('complaint')
    .update(patch)
    .eq('id', input.complaint_id)
  if (uErr) return { ok: false, error: uErr.message }

  await supabase.from('complaint_stage_history').insert({
    tenant_id: profile.tenant_id,
    complaint_id: input.complaint_id,
    from_stage_id: current.current_stage_id,
    to_stage_id: toId,
    actor_id: profile.id,
    remark: input.remark ?? null,
  })

  revalidatePath(`/complaints/${input.complaint_id}`)
  revalidatePath('/complaints')
  return { ok: true, data: { new_stage_id: toId } }
}

// ─── assignToEngineer ────────────────────────────────────────────

export async function assignComplaint(input: {
  complaint_id: string
  assignee_id: string
}): Promise<Result> {
  const auth = await requireProfile()
  if (!auth.ok) return auth
  const { supabase, profile } = auth

  // Confirm assignee exists in this tenant
  const { data: assignee } = await supabase
    .from('user_profile')
    .select('id, role')
    .eq('id', input.assignee_id)
    .single()
  if (!assignee) return { ok: false, error: 'Assignee not found in this tenant' }

  const { error: uErr } = await supabase
    .from('complaint')
    .update({
      assignee_id: input.assignee_id,
      assigned_at: new Date().toISOString(),
      assigned_by: profile.id,
      updated_by: profile.id,
      updated_at: new Date().toISOString(),
    })
    .eq('id', input.complaint_id)
  if (uErr) return { ok: false, error: uErr.message }

  // Advance to 'assigned' stage if currently logged/triaged
  const { data: current } = await supabase
    .from('complaint')
    .select('current_stage_id, complaint_stage:current_stage_id(stage_key)')
    .eq('id', input.complaint_id)
    .single()
  const stageKey = (current?.complaint_stage as { stage_key: string } | { stage_key: string }[] | null)
  const key = Array.isArray(stageKey) ? stageKey[0]?.stage_key : stageKey?.stage_key
  if (key === 'logged' || key === 'triaged') {
    await advanceComplaintStage({
      complaint_id: input.complaint_id,
      to_stage_key: 'assigned',
      remark: 'Auto-advance on assignment',
    })
  }

  revalidatePath(`/complaints/${input.complaint_id}`)
  revalidatePath('/complaints')
  return { ok: true, data: undefined }
}

// ─── recordResolution ────────────────────────────────────────────

export async function recordComplaintResolution(input: {
  complaint_id: string
  resolution_notes: string
  root_cause?: string
}): Promise<Result> {
  const auth = await requireProfile()
  if (!auth.ok) return auth
  const { supabase, profile } = auth

  if (!input.resolution_notes.trim()) {
    return { ok: false, error: 'Resolution notes are required' }
  }

  // Write resolution payload + advance to 'resolved' in one transaction-shape:
  // first update with the notes, then advance. (We don't have true tx here but
  // re-running is idempotent for these fields.)
  const { error: uErr } = await supabase
    .from('complaint')
    .update({
      resolution_notes: input.resolution_notes.trim(),
      root_cause: input.root_cause?.trim() ?? null,
      updated_by: profile.id,
      updated_at: new Date().toISOString(),
    })
    .eq('id', input.complaint_id)
  if (uErr) return { ok: false, error: uErr.message }

  // Advance — guard already enforces resolution_notes is set (we just set it)
  const adv = await advanceComplaintStage({
    complaint_id: input.complaint_id,
    to_stage_key: 'resolved',
    remark: 'Resolution recorded',
  })
  if (!adv.ok) return adv

  return { ok: true, data: undefined }
}

// ─── closeComplaint ──────────────────────────────────────────────

export async function closeComplaint(input: {
  complaint_id: string
  remark?: string
}): Promise<Result<{ new_stage_id: string }>> {
  return advanceComplaintStage({
    complaint_id: input.complaint_id,
    to_stage_key: 'closed',
    remark: input.remark ?? 'Closed',
  })
}

// ─── rejectComplaint (off-pipeline) ──────────────────────────────

export async function rejectComplaint(input: {
  complaint_id: string
  remark: string  // required — must explain why
}): Promise<Result<{ new_stage_id: string }>> {
  if (!input.remark.trim()) return { ok: false, error: 'Rejection reason is required' }
  return advanceComplaintStage({
    complaint_id: input.complaint_id,
    to_stage_key: 'rejected',
    remark: input.remark,
  })
}

// ─── listComplaints (read-only, for /complaints page) ────────────

export type ComplaintListRow = {
  id: string
  complaint_number: string
  title: string
  firm_name: string | null
  severity_label: string
  severity_color: string
  stage_label: string
  stage_color: string
  is_open: boolean
  assignee_name: string | null
  logged_at: string
}

export async function listComplaints(opts: {
  is_open?: boolean
  assignee_id?: string
  limit?: number
} = {}): Promise<Result<ComplaintListRow[]>> {
  const auth = await requireProfile()
  if (!auth.ok) return auth
  const { supabase } = auth

  let q = supabase
    .from('complaint')
    .select(`
      id, complaint_number, title, logged_at,
      firm:firm_id(name),
      severity:severity_id(label, color),
      stage:current_stage_id(label, color, is_open),
      assignee:assignee_id(full_name)
    `)
    .order('logged_at', { ascending: false })
    .limit(opts.limit ?? 100)

  if (opts.is_open !== undefined) {
    // Filter requires a join — use a subquery via the stage relationship
    // PostgREST doesn't filter on joined columns directly, so we fetch all
    // and filter in JS. Acceptable since complaint volumes are bounded.
  }
  if (opts.assignee_id) q = q.eq('assignee_id', opts.assignee_id)

  const { data, error } = await q
  if (error) return { ok: false, error: error.message }

  type Raw = {
    id: string
    complaint_number: string
    title: string
    logged_at: string
    firm: { name: string } | { name: string }[] | null
    severity: { label: string; color: string } | { label: string; color: string }[] | null
    stage: { label: string; color: string; is_open: boolean } | { label: string; color: string; is_open: boolean }[] | null
    assignee: { full_name: string } | { full_name: string }[] | null
  }
  const pick = <T,>(v: T | T[] | null): T | null => Array.isArray(v) ? (v[0] ?? null) : v

  let rows: ComplaintListRow[] = (data as Raw[] ?? []).map((r) => {
    const stage = pick(r.stage)
    const severity = pick(r.severity)
    return {
      id: r.id,
      complaint_number: r.complaint_number,
      title: r.title,
      logged_at: r.logged_at,
      firm_name: pick(r.firm)?.name ?? null,
      severity_label: severity?.label ?? '—',
      severity_color: severity?.color ?? '#94a3b8',
      stage_label: stage?.label ?? '—',
      stage_color: stage?.color ?? '#94a3b8',
      is_open: stage?.is_open ?? false,
      assignee_name: pick(r.assignee)?.full_name ?? null,
    }
  })

  if (opts.is_open !== undefined) {
    rows = rows.filter((r) => r.is_open === opts.is_open)
  }

  return { ok: true, data: rows }
}
