'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'

async function getActorContext() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null

  const { data: profile } = await supabase
    .from('user_profile')
    .select('tenant_id, role')
    .eq('id', user.id)
    .single()

  if (!profile) return null
  return { supabase, userId: user.id, tenantId: profile.tenant_id, role: profile.role }
}

export async function createQuotation(data: {
  project_id: string
  notes?: string
  valid_until?: string
  lines: Array<{ product_id: string; quantity: number; unit_price: number; description?: string; price_list_entry_id?: string | null }>
}): Promise<{ id: string; quotation_number: string } | { error: string }> {
  const ctx = await getActorContext()
  if (!ctx) return { error: 'Not authenticated' }

  const { supabase, userId, tenantId } = ctx

  if (!data.lines || data.lines.length === 0) {
    return { error: 'At least one line item is required' }
  }

  // Resolve product snapshots for each line (schema requires product_name, sku_code, unit NOT NULL)
  const productIds = Array.from(new Set(data.lines.map((l) => l.product_id)))
  const { data: productsData, error: productsErr } = await supabase
    .from('product')
    .select('id, sku_code, name, unit')
    .in('id', productIds)
  if (productsErr) {
    console.error('createQuotation product lookup error', productsErr)
    return { error: productsErr.message }
  }
  const productsById = Object.fromEntries(
    (productsData ?? []).map((p) => [p.id, p as { id: string; sku_code: string; name: string; unit: string }])
  )
  for (const l of data.lines) {
    if (!productsById[l.product_id]) {
      return { error: `Product ${l.product_id} not found` }
    }
  }

  const subtotal = data.lines.reduce((sum, l) => sum + l.quantity * l.unit_price, 0)
  const total = subtotal // discount applied later if added; subtotal == total when discount_pct = 0

  // Header insert — quotation_number is auto-generated by trg_quotation_number
  const { data: quotation, error: quotationError } = await supabase
    .from('quotation')
    .insert({
      tenant_id: tenantId,
      project_id: data.project_id,
      status: 'draft',
      subtotal,
      discount_pct: 0,
      total,
      valid_until: data.valid_until ?? null,
      notes: data.notes ?? null,
      created_by: userId,
      updated_by: userId,
    })
    .select('id, quotation_number')
    .single()

  if (quotationError) {
    console.error('createQuotation error', quotationError)
    return { error: quotationError.message }
  }

  const lineRows = data.lines.map((line, i) => {
    const p = productsById[line.product_id]
    return {
      tenant_id: tenantId,
      quotation_id: quotation.id,
      product_id: line.product_id,
      product_name: p.name,
      sku_code: p.sku_code,
      unit: p.unit,
      quantity: line.quantity,
      unit_price: line.unit_price,
      discount_pct: 0,
      line_total: line.quantity * line.unit_price,
      notes: line.description ?? null,
      sort_order: i,
      price_list_entry_id: line.price_list_entry_id ?? null,
    }
  })

  const { error: linesError } = await supabase
    .from('quotation_line')
    .insert(lineRows)

  if (linesError) {
    console.error('createQuotation lines error', linesError)
    return { error: linesError.message }
  }

  // Activity timeline is auto-written by trg_quotation_activity trigger on INSERT —
  // we do NOT insert manually, to avoid duplicate rows.

  revalidatePath(`/projects/${data.project_id}`)
  return { id: quotation.id, quotation_number: quotation.quotation_number as string }
}

export async function updateQuotationStatus(
  quotationId: string,
  status: 'sent' | 'won' | 'lost',
  notes?: string
): Promise<{ success: true } | { error: string }> {
  const ctx = await getActorContext()
  if (!ctx) return { error: 'Not authenticated' }

  const { supabase, userId, tenantId } = ctx

  const { data: existing, error: fetchError } = await supabase
    .from('quotation')
    .select('project_id, quotation_number, total, status')
    .eq('id', quotationId)
    .single()

  if (fetchError || !existing) return { error: 'Quotation not found' }

  // Map UI status names to DB status enum (schema CHECK: draft|sent|revised|accepted|rejected|expired)
  // 'won' → 'accepted'; 'lost' → 'rejected'
  const dbStatus: 'sent' | 'accepted' | 'rejected' =
    status === 'sent' ? 'sent' : status === 'won' ? 'accepted' : 'rejected'

  const updatePayload: Record<string, unknown> = {
    status: dbStatus,
    updated_by: userId,
    updated_at: new Date().toISOString(),
  }

  if (dbStatus === 'sent') {
    updatePayload.sent_at = new Date().toISOString()
  }
  if (dbStatus === 'accepted') {
    updatePayload.accepted_at = new Date().toISOString()
  }
  if (notes) {
    updatePayload.notes = notes
  }

  const { error } = await supabase
    .from('quotation')
    .update(updatePayload)
    .eq('id', quotationId)

  if (error) {
    console.error('updateQuotationStatus error', error)
    return { error: error.message }
  }

  if (dbStatus === 'accepted') {
    await supabase
      .from('project')
      .update({ won_quote_id: quotationId })
      .eq('id', existing.project_id)

    // Emit quote.won so the Order module can react (Slice 2 listener)
    try {
      const { inngest } = await import('@/lib/inngest/client')
      await inngest.send({
        name: 'quote.won',
        data: { quote_id: quotationId, order_value: Number(existing.total ?? 0) },
      })
    } catch (e) {
      // Non-blocking; log only
      console.error('Failed to emit quote.won', e)
    }
  }

  // No manual activity insert — trg_quotation_activity trigger writes 'quote_sent' on
  // sent transition automatically. Won/lost/etc. do not have automatic timeline entries;
  // if needed, add a generic 'updated' activity here. For Slice 1 parity, leaving silent.
  // (Tenant context kept for future use)
  void tenantId

  revalidatePath(`/projects/${existing.project_id}`)
  return { success: true }
}
